services:
  fastapi_app_capstone:
    build: .
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # Montamos el código local dentro del contenedor
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
